name: noop_benchmark_depth_1_size_0_mode_ref
pipelines:
- name: NoOp Chain Depth 1 Size 0 Mode ref
  inputs:
  - 0
  outputs:
  - 0
  dataset_stage_id: 0
  loadgen:
    component: loadgen.OfflineLoadScheduler
    queue_depth: 100
    max_queries: 101
    timeout: 60000
    config:
      rate: 0
  stages:
  - name: Ref Stage 0
    id: 0
    component: stages.stage.Stage
    outputs: []
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
    config: {}
