name: "PHI3 Mini Alpaca generation pipeline"
pipelines:
  - name: Alpaca generation
    inputs: [0]
    outputs: [1]
    dataset_stage_id: 0
    loadgen:
      component: loadgen.OfflineLoadScheduler
      queue_depth: 10
      max_queries: 2000
      timeout: 20000
      config:
        rate: 1 # average #requests/sec
    stages:
      - name: Alpaca dataloader
        id: 0
        outputs: [1]
        component: stages.llm_torchtune.TorchTuneDataLoader
        config:
          batch_size: 1
          shuffle: True
          split: ["val"]
          dataset:
            component: torchtune.datasets.alpaca_cleaned_dataset
          tokenizer:
            component: torchtune.models.qwen2_5.qwen2_5_tokenizer
            path: tmp/Qwen2.5-0.5B-Instruct/vocab.json
            merges_file: tmp/Qwen2.5-0.5B-Instruct/merges.txt
      - name: Alpaca inference
        id: 1
        component: stages.llm_torchtune.Inference
        config: 
          dtype: torch.bfloat16
          device: cuda
          temperature: 0.6
          top_k: 300
          max_new_tokens: 300
          batch_size_stage_id: 0
          tokenizer_stage_id: 0
          model:
            component: torchtune.models.qwen2_5.qwen2_5_0_5b
            KV_cache: true
          checkpointer:
            component: torchtune.utils.FullModelHFCheckpointer
            checkpoint_dir: tmp/Qwen2.5-0.5B-Instruct
            checkpoint_files: [
              model.safetensors
            ]
            output_dir: tmp/Qwen2.5-0.5B-out
            model_type: QWEN2