name: "Self RAG"
pipelines:
  - name: Self RAG
    inputs: [0]
    outputs: [1]
    dataset_stage_id: 0
    loadgen:
      component: loadgen.OfflineLoadScheduler
      queue_depth: 10
      max_queries: 10
      timeout: 20000
      config:
        rate: 1 # average #requests/sec
    stages:
      - name: RAG questions dataloader
        id: 0
        outputs: [1]
        component: stages.self_rag.RAGDataLoader
        config:
          tokenizer_stage_id: 1
          batch_size: 1
      - name: RAG infer
        id: 1
        component: stages.llm_huggingface.Inference
        config: 
          dtype: torch.bfloat16
          device: cuda
          # data_model: utils.schemas.rag.RouterAnswer
          model:
            name: microsoft/Phi-3-mini-4k-instruct
            quantize: False
            temperature: 0
      # - name: SQLite query
      #   id: 2
      #   component: stages.self_rag.SQLiteSearch
      #   config:
      #     db_path: tmp/accounting.sqlite