name: "ResNet50-v1.5 implementation of MLPerf Inference v5.0"
pipelines:
  - name: ResNet50-v1.5 inference
    inputs: [0]
    outputs: [1]
    dataset_stage_id: 0
    loadgen:
      component: loadgen.PoissonLoadScheduler
      max_queries: 200
      timeout: 30
      queue_depth: 10
      config:
        rate: 10 # average #requests/sec
    stages:
      - name: Load Imagenet samples from TorchVision Dataset
        id: 0
        outputs: [1]
        component: stages.torchvision_classification.TorchVisionDataLoader
        polling_policy: utils.queues.polling.SingleQueuePolicy
        disable_logs: false
        config:
          batch_size: 8
          preprocess: True
          preload: False
          num_workers: 0 # if 0 no prefetching else prefetches 2*num_workers samples
          dataset:
            component: torchvision.datasets.ImageNet
            weights: ResNet50_Weights.IMAGENET1K_V2
            split: [val]
      - name: EfficientNet inference
        id: 1
        outputs: []
        component: stages.torchvision_classification.TorchVisionClassification
        polling_policy: utils.queues.polling.SingleQueuePolicy
        disable_logs: false
        config:
          model: 
            component: torchvision.models.resnet50
            weights: ResNet50_Weights.IMAGENET1K_V2
          device: cuda