name: bg_clipgpu_L100_cuda
pipelines:
- name: BG co-runner clipgpu
  dataset_stage_id: 0
  inputs:
  - 0
  outputs:
  - 1
  loadgen:
    component: loadgen.MultiStreamScheduler
    queue_depth: 1000
    max_queries: 19628
    timeout: 1397
    config:
      interval: 0.0356
  stages:
  - name: VQA dataloader
    id: 0
    outputs:
    - 1
    component: stages.multimodal_vqa.VQADataLoader
    config:
      dataset:
        name: Multimodal-Fatima/OK-VQA_train
        split: train
        image_column: image
        question_column: question
        answers_column: answers
        max_samples: 100
      batch_size: 1
  - name: CLIP vision encoder
    id: 1
    component: stages.multimodal_vqa.CLIPVisionEncoder
    config:
      model:
        name: openai/clip-vit-large-patch14
      device: cuda
