name: bg_stream_L25_mlx
pipelines:
- name: BG co-runner stream
  dataset_stage_id: 0
  inputs:
  - 0
  outputs:
  - 0
  loadgen:
    component: loadgen.MultiStreamScheduler
    queue_depth: 1000
    max_queries: 2937
    timeout: 1397
    config:
      interval: 0.23798
  stages:
  - name: CPU memory stream
    id: 0
    component: stages.evaluation.MemoryStream
    config:
      size_mb: 256
      passes: 4
