name: E2 modularity efficientnet_v2_s batch 32 (cuda)
listeners: []
pipelines:
- name: EfficientNetv2 S Imagenette training
  inputs:
  - 0
  outputs:
  - 1
  dataset_stage_id: 0
  serialize_queries: true
  loadgen:
    component: loadgen.OfflineLoadScheduler
    queue_depth: 10
    max_queries: 1000
    timeout: 300000
    config:
      rate: 0
  stages:
  - name: Load Imagenette samples from TorchVision Dataset
    id: 0
    outputs:
    - 1
    component: stages.torchvision_classification.TorchVisionDataLoader
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
    config:
      batch_size: 32
      preprocess: true
      num_workers: 0
      dataset:
        component: torchvision.datasets.Imagenette
        split:
        - train
        weights: EfficientNet_V2_S_Weights.IMAGENET1K_V1
  - name: EfficientNet training
    id: 1
    outputs: []
    component: stages.torchvision_classification.TorchVisionClassification
    polling_policy: utils.queues.polling.SingleQueuePolicy
    disable_logs: false
    config:
      model:
        component: torchvision.models.efficientnet_v2_s
        replace_classifier: true
        num_classes: 10
      optimizer:
        component: torch.optim.Adam
        lr: 0.001
      criterion:
        component: torch.nn.CrossEntropyLoss
      device: cuda
